version: "3.1"

services:
  spk_mst:
    image: mkenjis/ubspkcluster_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdpmst
    environment:
      - SPARK_HOST_SLAVES=spk1,spk2
    networks:
      - mynet
    depends_on:
      - spk1,spk2
    ports:
      - 4040:4040
      - 8080:8080
  spk1:
    image: mkenjis/ubspkcluster_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp1
    networks:
      - mynet
  spk2:
    image: mkenjis/ubspkcluster_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp2
    networks:
      - mynet

  mysql:
    image: mysql:5.7
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp3
    networks:
      - mynet
    environment:
      - MYSQL_ROOT_PASSWORD=admsys123
      - MYSQL_DATABASE=metastore
      - MYSQL_USER=hiveuser
      - MYSQL_PASSWORD=hive123
    volumes:
      - .:/root/staging
      - db:/var/lib/mysql

networks:
  mynet:
    external:
       name: mynet

volumes:
  db: